src/main/java/com/selivanov/model/OntologyTask.java
package com.selivanov.model;

import org.apache.jena.ontology.Individual;

import java.util.ArrayList;

public class OntologyTask {
    String task;
    ArrayList<String> answers;
    String answer;
    String correctAnswer;
    String individual;

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    public ArrayList<String> getAnswers() {
        return answers;
    }

    public void setAnswers(ArrayList<String> answers) {
        this.answers = answers;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getCorrectAnswer() {
        return correctAnswer;
    }

    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

    public boolean isCorrect() {
        if(answer!=null && answer.equals(correctAnswer))
            return true;
        else
            return false;
    }

    public String getIndividual() {
        return individual;
    }

    public void setIndividual(String individual) {
        this.individual = individual;
    }
}

src/main/java/com/selivanov/controller/TaskController.java
package com.selivanov.controller;

import com.selivanov.dao.OntologyDataDAO;
import com.selivanov.model.OntologyData;
import com.selivanov.model.OntologyTask;
import com.selivanov.model.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import java.util.ArrayList;

@Controller
public class TaskController {

    public static OntologyDataDAO dao = new OntologyDataDAO();

    public static User tempUser = null;
    public static boolean login = false;

    @RequestMapping(value = "/task", method = RequestMethod.GET)
    public ModelAndView tasksForm(String type){
        ModelAndView modelAndView = new ModelAndView("task");
        modelAndView.addObject("taskType", type);

        OntologyData ontologyData = new OntologyData();
        ArrayList<OntologyTask> tasks;

        if(login){
            if(type!=null && type.equals("derivatives")){
                tasks = dao.generateTasksByTopic("SumOfDerivative");
                ontologyData.setTasks(tasks);
            }
            else if(type!=null && type.equals("integrals")){
                tasks = dao.generateTasksByTopic("SumOfDerivative");
                ontologyData.setTasks(tasks);
            }
            else {
                return new ModelAndView("error");
            }
        }
        else {
            return new ModelAndView("error");
        }

        modelAndView.addObject("data", ontologyData);

        return modelAndView;
    }

    @RequestMapping(value = "/task", method = RequestMethod.POST)
    public ModelAndView submit(OntologyData data){
        ModelAndView modelAndView = new ModelAndView("answer");
        modelAndView.addObject("data", data);

        String temp_task = null;
        modelAndView.addObject("temp_task", temp_task);

        ArrayList<OntologyTask> wrongAnswers = new ArrayList<OntologyTask>();
        ArrayList<OntologyTask> correctAnswers = new ArrayList<OntologyTask>();

        for (OntologyTask task:data.getTasks()) {
            if(!task.isCorrect()){
                wrongAnswers.add(task);
                dao.addProblemTaskToUser(tempUser, task);
            }
            else {
                dao.removeFromProblemTasks(tempUser, task);
            }
        }

        modelAndView.addObject("numberOfRightAnswers", data.getTasks().size() - wrongAnswers.size());
        modelAndView.addObject("numberOfTasks", data.getTasks().size());

        return modelAndView;
    }

    @RequestMapping(value = "/learn", method = RequestMethod.GET)
    public ModelAndView learnForm(String task_id){
        ModelAndView modelAndView = new ModelAndView("learn");

        OntologyData ontologyData = new OntologyData();
        OntologyTask task = dao.getTaskById(task_id);

        ArrayList<OntologyTask> arr = new ArrayList<>();
        arr.add(task);
        ontologyData.setTasks(dao.getTasksByProperty(arr, "hasRelativeTask"));

        modelAndView.addObject("data", ontologyData);
        modelAndView.addObject("task_def", task.getTask());

        return modelAndView;
    }

}

web/WEB-INF/views/answer.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<%@ include file="common/head.jsp"%>
<body>
<%@ include file="common/header.jsp"%>
<main>
    <div class="container">
        <div class="col-md-12">
            <br>
            <h3>Results</h3>
            <c:forEach var="task" items="${data.tasks}">
                <div class="card">
                    <div class="card-header">${task.task}</div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Your answer is ${task.answer}</li>

                            <c:choose>
                                <c:when test="${task.correct}">
                                    <li class="list-group-item bg-success text-white">Correct</li>
                                </c:when>
                                <c:otherwise>
                                    <li class="list-group-item bg-danger text-white">
                                        Wrong! <a class="btn btn-dark" href="/learn?task_id=${task.individual}" role="button">Learn</a>
                                    </li>
                                </c:otherwise>
                            </c:choose>

                    </ul>
                </div>
                <br>
            </c:forEach>

            <h3>Your result: ${numberOfRightAnswers} from ${numberOfTasks}</h3>

            <br>
            <br>

        </div>

        <hr>
    </div>
</main>
<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>
</body>
</html>


web/WEB-INF/views/error.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!doctype html>
<html lang="en">

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <div class="container">
        <div class="col-md-12">
            <br>
            <h1>Error</h1>
        </div>

        <hr>

    </div> <!-- /container -->

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>


web/WEB-INF/views/hello.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Hello page</title>
</head>
<body>
    <p>Hello, ${user.username}</p>

</body>
</html>

web/WEB-INF/views/index.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!doctype html>
<html lang="en">

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">Math Quiz</h1>
            <p>Math quiz web application based on ontology and description logic.</p>
            <%--<p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>--%>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Derivatives</h2>
                <p>Test your knowledge of derivatives.</p>
                <%--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>--%>
                <p><a class="btn btn-secondary" href="/task?type=derivatives" role="button">Go to test &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Integrals</h2>
                <p>Test your knowledge of integrals.</p>
                <%--<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>--%>
                <p><a class="btn btn-secondary" href="#" role="button">Go to test &raquo;</a></p>
            </div>
            <div class="col-md-4">
                <h2>Logarithms</h2>
                <p>Test your knowledge of logarithms.</p>
                <%--<p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>--%>
                <p><a class="btn btn-secondary" href="#" role="button">Go to test
                    &raquo;</a></p>
            </div>
        </div>

        <hr>

    </div> <!-- /container -->

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>


web/WEB-INF/views/learn.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@ page isELIgnored ="false" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <div class="container">
        <div class="col-md-12">

            <br>
            <h3>Learn ${task_def}</h3>

            <spring:form modelAttribute="data" action="task" method="post">
                <c:forEach items="${data.tasks}" varStatus="status" var="task">
                    <spring:hidden path="tasks[${status.index}].correctAnswer" title="${task.correctAnswer}" />
                    <spring:hidden path="tasks[${status.index}].task" title="${task.task}" />
                    <spring:hidden path="tasks[${status.index}].individual" title="${task.individual}"></spring:hidden>

                    <div class="card">
                        <div class="card-header">${task.task}</div>
                        <div class="card-body">
                            <c:forEach items="${task.answers}" var="tempAnswer">
                                <div class="form-check">
                                    <spring:radiobutton cssClass="form-check-input" path="tasks[${status.index}].answer" value="${tempAnswer}"/>
                                    <label class="form-check-label" for="${tempAnswer}">
                                            ${tempAnswer}
                                    </label>
                                </div>
                            </c:forEach>
                        </div>
                    </div>
                    <br>
                </c:forEach>
                <button type="submit" class="btn btn-primary">Submit</button>
            </spring:form>
        </div>

        <hr>
    </div>

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>



web/WEB-INF/views/login.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@ page isELIgnored ="false" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <div class="container">
        <div class="col-md-12">

            <br>
            <h3>Log In</h3>
            <br>

            <spring:form method="post" action="login" modelAttribute="user">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </spring:form>

            <br>
            <a href="/register">Sign In</a>

        </div>

        <hr>
    </div>

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>



web/WEB-INF/views/profile.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<html>
<%@ include file="common/head.jsp"%>
<body>
<%@ include file="common/header.jsp"%>
<main>
    <div class="container">
        <div class="col-md-12">
            <br>
            <h3>${user.email}</h3>
            <h4>Problem tasks:</h4>
            <c:forEach var="task" items="${user.problemTasks}">
                <div class="card">
                    <div class="card-header">${task.task}</div>
                    <div class="card-body">
                        <a class="btn btn-dark" href="/learn?task_id=${task.individual}" role="button">Learn</a>
                    </div>
                </div>
                <br>
            </c:forEach>

            <br>
            <br>

        </div>

        <hr>
    </div>
</main>
<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>
</body>
</html>


web/WEB-INF/views/register.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@ page isELIgnored ="false" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <div class="container">
        <div class="col-md-12">

            <br>
            <h3>Sign In</h3>
            <br>

            <spring:form method="post" action="register" modelAttribute="user">
                <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </spring:form>

        </div>

        <hr>
    </div>

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>



web/WEB-INF/views/successRegister.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@ page isELIgnored ="false" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <div class="container">
        <div class="col-md-12">

            <br>

            Successful registration!

        </div>

        <hr>
    </div>

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>



web/WEB-INF/views/task.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@ page isELIgnored ="false" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>

<%@ include file="common/head.jsp"%>

<body>

<%@ include file="common/header.jsp"%>

<main role="main">

    <div class="container">
        <div class="col-md-12">

            <br>
            <h3>Test ${taskType}</h3>

            <spring:form modelAttribute="data" action="task" method="post">
                <c:forEach items="${data.tasks}" varStatus="status" var="task">
                    <spring:hidden path="tasks[${status.index}].correctAnswer" title="${task.correctAnswer}" />
                    <spring:hidden path="tasks[${status.index}].task" title="${task.task}" />
                    <spring:hidden path="tasks[${status.index}].individual" title="${task.individual}"></spring:hidden>

                    <div class="card">
                        <div class="card-header">${task.task}</div>
                        <div class="card-body">
                            <c:forEach items="${task.answers}" var="tempAnswer">
                                <div class="form-check">
                                    <spring:radiobutton cssClass="form-check-input" path="tasks[${status.index}].answer" value="${tempAnswer}"/>
                                    <label class="form-check-label" for="${tempAnswer}">
                                            ${tempAnswer}
                                    </label>
                                </div>
                            </c:forEach>
                        </div>
                    </div>
                    <br>
                </c:forEach>
                <button type="submit" class="btn btn-primary">Submit</button>
            </spring:form>
        </div>

        <hr>
    </div>

</main>

<%@ include file="common/footer.jsp"%>
<%@ include file="common/scripts.jsp"%>

</body>
</html>

